# Generated by Django 2.1.1 on 2018-09-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do Fornecedor', max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Informe o CPF do fornecedor', max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'ordering': ['nome'],
            },
        ),
    ]
