# Generated by Django 2.1.1 on 2018-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='cpf',
            field=models.CharField(help_text='Informe o CPF do organizador', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='nome',
            field=models.CharField(help_text='Informe o nome do organizador', max_length=50, verbose_name='Nome'),
        ),
    ]
