# Generated by Django 2.1.1 on 2018-09-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe o nome do participante', max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(help_text='Informe o CPF do participante', max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('rg', models.CharField(help_text='Informe o RG do participante', max_length=11, verbose_name='RG')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Não credenciado'), (1, 'Credenciado')], verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['nome'],
            },
        ),
    ]
