# Generated by Django 2.1.1 on 2018-09-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Informe o título do evento', max_length=50, verbose_name='Título')),
                ('data_hora', models.DateTimeField(verbose_name='Data/Hora')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Congresso'), (2, 'Seminário'), (3, 'Workshop'), (4, 'Oficina')], verbose_name='Toipo')),
                ('local', models.CharField(help_text='Informe o local do evento', max_length=150, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_hora'],
            },
        ),
    ]
