# Generated by Django 2.1.1 on 2018-09-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Congresso'), (2, 'Seminário'), (3, 'Workshop'), (4, 'Oficina')], verbose_name='Tipo'),
        ),
    ]
