# Generated by Django 2.1.1 on 2018-09-24 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evento', '0002_auto_20180922_0641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data', '-data'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='evento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
            preserve_default=False,
        ),
    ]
